name: test

on: push

jobs:
  build:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: test
        id: dependency
        run: pnpm init && pnpm add github:TypeStrong/ts-node#main
